name: Build Executable (Windows)

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m venv venv
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          Invoke-WebRequest -Uri 'https://dependencywalker.com/depends22_x64.zip' -Outfile 'depends.zip'
          Expand-Archive -Path depends.zip 'C:\Users\runneradmin\AppData\Local\Nuitka\Nuitka\Cache\downloads\depends\x86_64'
      - name: Build package
        run: |
          venv\Scripts\Activate.ps1
          pyside6-deploy -c pysidedeploy_windows.spec
      - name: Upload executable
        run:
          gh release upload ${{ github.event.release.tag_name }} bin/photo-prune_windows.exe
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
